a = int(input("Введите число a: "))
b = int(input("Введите число b: "))
x = int(input("Введите число x: "))
y = int(input("Введите число y: "))
print("a) 2 кг б) a1 в) xy")
print("13 17      19b   5y")
